Repository notsogreatdavi/DSI-2024.2, pull requests merged in 2025-02, with the labels that each got.

#13 📝 Card-001 Aprimoramento da Tela de Atividades
  flutter_application_1/android/app/src/main/AndroidManifest.xml
  flutter_application_1/ios/Runner/Info.plist
  flutter_application_1/lib/build/.last_build_id
  flutter_application_1/lib/main.dart
  flutter_application_1/lib/src/features/activities/activities_screen.dart
  flutter_application_1/lib/src/features/home/home_screen.dart
  flutter_application_1/lib/src/features/registers/delete_group.dart
  flutter_application_1/lib/src/features/registers/register_class.dart
  flutter_application_1/linux/flutter/generated_plugin_registrant.cc
  flutter_application_1/linux/flutter/generated_plugins.cmake
  flutter_application_1/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_application_1/pubspec.lock
  flutter_application_1/pubspec.yaml
  flutter_application_1/windows/flutter/generated_plugin_registrant.cc
  flutter_application_1/windows/flutter/generated_plugins.cmake
Labels: documentation, enhancement, bugsfixes

#14 📝 Card-002 Envio de imagens adicionado
  flutter_application_1/lib/src/features/home/home_screen.dart
  flutter_application_1/lib/src/features/registers/register_class.dart
  flutter_application_1/pubspec.lock
  flutter_application_1/pubspec.yaml
Labels: enhancement

#15 📝Card-003 Criação dos recursos de adicionar/editar/apagar atividades
  flutter_application_1/lib/app.dart
  flutter_application_1/lib/src/features/activities/activities_screen.dart
  flutter_application_1/lib/src/features/activities/create_activity.dart
  flutter_application_1/lib/src/features/activities/update-delete_activity.dart
  flutter_application_1/pubspec.yaml
Labels: documentation, enhancement

#16 Feature/navbar
  flutter_application_1/.gitignore
  flutter_application_1/lib/app.dart
  flutter_application_1/lib/src/common/widgets/custom_bottom_navigation_bar.dart
  flutter_application_1/lib/src/features/activities/activities_screen.dart
  flutter_application_1/lib/src/features/home/home_screen.dart
  flutter_application_1/lib/src/features/pomodoro/pomodoro_screen.dart
  flutter_application_1/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_application_1/pubspec.lock
  flutter_application_1/pubspec.yaml
Labels: enhancement

#17 Feature/tela mapa
  flutter_application_1/android/app/src/main/AndroidManifest.xml
  flutter_application_1/lib/app.dart
  flutter_application_1/lib/src/common/widgets/custom_bottom_navigation_bar.dart
  flutter_application_1/lib/src/features/activities/activities_screen.dart
  flutter_application_1/lib/src/features/map/map_screen.dart
  flutter_application_1/pubspec.lock
  flutter_application_1/pubspec.yaml
Labels: enhancement, bugsfixes

#18 📝 Card-004 Atualização da lógica de criação de atividade
  flutter_application_1/lib/src/features/activities/create_activity.dart
  flutter_application_1/lib/src/features/activities/update-delete_activity.dart
Labels: enhancement

#21 📝 Card-005 Aprimoramento Tela Mapa e Ajustes Navbar
  flutter_application_1/lib/app.dart
  flutter_application_1/lib/src/features/activities/activities_screen.dart
  flutter_application_1/lib/src/features/map/map_screen.dart
  flutter_application_1/lib/src/features/pomodoro/pomodoro_screen.dart
  flutter_application_1/lib/src/features/ranking/ranking_screen.dart
Labels: enhancement, bugsfixes

#23 📝 Card-007 Tela de pomodoro aprimorada e salvamento no banco de dados ajustado
  flutter_application_1/lib/app.dart
  flutter_application_1/lib/src/features/activities/activities_screen.dart
  flutter_application_1/lib/src/features/map/map_screen.dart
  flutter_application_1/lib/src/features/pomodoro/pomodoro_screen.dart
  flutter_application_1/lib/src/features/ranking/ranking_screen.dart
Labels: enhancement, bugsfixes

#24 📝 Card-008 Tela de ranking finalizada
  flutter_application_1/lib/src/common/widgets/custom_navigation_bar.dart
  flutter_application_1/lib/src/features/ranking/ranking_screen.dart
Labels: enhancement, bugsfixes
